version: '3.7'

services:
  web:
    build: "./linux"
    # vscodeでデバッグするためにホスト追加
    container_name: "assignment_web"
    # platform: linux/amd64
    # environment:
    #   - SMTP_HOST=assignment_mailhog
    #   - SMTP_PORT=1025
    ports:
      - 80:80
    # コンテナに配置するファイルの場所、webアプリケーションの構成に合わせて変更
    volumes:
      - ../:/var/www/
    privileged: true
    # tty: true
    # stdin_open: true
    depends_on:
      - mysql
    networks:
      - br0
  mysql:
    #mysqlのバージョンに合わせて変更
    image: mysql:8.0.31
    container_name: "assignment_db"
    # platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'assignment'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    networks:
      - br0
  phpmyadmin:
    container_name: "assignment_phpmyadmin"
    # platform: linux/amd64
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    networks:
      - br0
  mailhog:
    image: mailhog/mailhog:latest
    container_name: assignment_mailhog
    # platform: linux/amd64
    # restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - br0
volumes:
  db_data: {}

networks:
  br0:
    driver: bridge
